### ISSUE TITLE
Zoom slider disappears on all views after map view

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#103]

**Comment by bijancfarahani** [comment]
I looked into this one and found some important information.  Firstly, the toolbar is in a <div> and is initially loaded like this.
`<div class="pv-toolbarpanel-zoomcontrols" style="border-width: 1px;"><div class="pv-toolbarpanel-zoomslider ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="display: block;"><span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" style="left: 0%;"></span></div></div>` 

After clicking map view, the div tag then has:
`display: none`
added to it.  This attribute is never removed when clicking on other views which is probably why this issue is occurring.

**Comment by bijancfarahani** [comment]
manually removing the attribute in the chrome developer tools brought the slider back.  I'm unsure where in the project the code regarding editing/loading the html is, but I think this is a good place to start.

**Comment by izaslavsky** [comment]
Thanks Bijan! Sounds like setting this div to display:block when a view icon (other than map) is clicked (or where a view is initialized), should do it. Sid, could you take a look?
